In [3]:
import numpy as np

my_arr = np.arange(1_000_000)

my_list = list(range(1_000_000))

In [5]:
%timeit my_arr2 = my_arr * 2

2.12 ms ± 73.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
%timeit my_list2 = [x * 2 for x in my_list]

117 ms ± 17.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [10]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [11]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

In [14]:
data1 = [6, 7.5, 8, 0, 1]

In [15]:
arr1 = np.array(data1)

In [16]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [18]:
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((2,3,2))

array([[[7.74662742e-312, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [5.43230922e-312, 1.33664410e+160]],

       [[4.26784010e-090, 4.04459737e-037],
        [2.38171535e+179, 2.87983449e+180],
        [3.99910963e+252, 1.72377181e-047]]])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [29]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr2.dtype

dtype('int32')

In [32]:
arr = np.array([1, 2, 3, 4, 5])

In [33]:
arr.dtype

dtype('int32')

In [34]:
float_arr = arr.astype(np.float64)

In [35]:
float_arr

array([1., 2., 3., 4., 5.])

In [36]:
float_arr.dtype

dtype('float64')

In [37]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [38]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [39]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [40]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [41]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [42]:
int_array = np.arange(10)

In [43]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [44]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [46]:
zeros_uint32 = np.zeros(8, dtype="u4")

In [47]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [48]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [49]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [50]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [51]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [53]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [54]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [55]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [56]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [57]:
arr = np.arange(10)

In [58]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr[5]

5

In [60]:
arr[5:8]

array([5, 6, 7])

In [61]:
arr[5:8] = 12

In [62]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [63]:
arr_slice = arr[5:8]

In [64]:
arr_slice

array([12, 12, 12])

In [65]:
arr_slice[1] = 12345

In [66]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [67]:
arr_slice[:] = 64

In [68]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [69]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [70]:
arr2d[2]

array([7, 8, 9])

In [71]:
arr2d[0][2]

3

In [72]:
arr2d[0, 2]

3

In [73]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [74]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
old_values = arr3d[0].copy()

In [77]:
arr3d[0] = 42

In [78]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr3d[0] = old_values

In [80]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [82]:
arr3d[1, 0]

array([7, 8, 9])

In [83]:
x = arr3d[1]

In [84]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [85]:
x[0]

array([7, 8, 9])