In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from pandas import Series, DataFrame

In [4]:
obj = pd.Series([4, 7, -5, 3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.array

<PandasArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2["a"]

-5

In [12]:
obj2["d"] = 6

In [13]:
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [14]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [15]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [16]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
"b" in obj2

True

In [18]:
"e" in obj2

False

In [19]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

In [20]:
obj3 = pd.Series(sdata)

In [21]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [23]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)

In [24]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [31]:
obj4.name = "population"

In [32]:
obj4.index.name = "state"

In [33]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [34]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [35]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]

In [36]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [37]:
data  = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [38]:
frame = pd.DataFrame(data)

In [39]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [40]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [41]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [42]:
pd.DataFrame(data, columns=["year", "state", "pop"])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [43]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

In [44]:
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [45]:
frame2.columns


Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [46]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [47]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [48]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [49]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [50]:
frame2["debt"] = 16.5

In [51]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [52]:
frame2["debt"] = np.arange(6.)

In [53]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [54]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])

In [55]:
frame2["debt"] = val

In [56]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [57]:
frame2["eastern"] = frame2["state"] == "Ohio"

In [58]:
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [59]:
del frame2["eastern"]

In [60]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [61]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}, 
              "Nevada": {2001: 2.4, 2002: 2.9}}

In [62]:
frame3 = pd.DataFrame(populations)

In [63]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [64]:
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [65]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [66]:
pdata = {"Ohio": frame3["Ohio"][:-1],
        "Nevada": frame3["Nevada"][:2]}

In [67]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [68]:
frame3.index.name = "year"

In [69]:
frame3.columns.name = "state"

In [70]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [71]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [72]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [73]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])

In [74]:
index = obj.index

In [75]:
index

Index(['a', 'b', 'c'], dtype='object')

In [76]:
index[1:]

Index(['b', 'c'], dtype='object')

In [77]:
index[1] = "d"

TypeError: Index does not support mutable operations

In [ ]:
labels = pd.Index(np.arange(3))

In [ ]:
labels

In [ ]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [ ]:
obj2

In [ ]:
obj2.index is labels

In [ ]:
frame3

In [ ]:
frame3.columns

In [ ]:
"Ohio" in frame3.columns

In [ ]:
2003 in frame3.index

In [ ]:
pd.Index(["foo", "foo", "bar", "bar"])

In [ ]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])

In [ ]:
obj

In [ ]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])

In [ ]:
obj2

In [ ]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

In [ ]:
obj3

In [ ]:
obj3.reindex(np.arange(6), method="ffill")

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index = ["a", "c", "d"], 
                    columns=["Ohio", "Texas", "California"])

In [ ]:
frame

In [ ]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])

In [ ]:
frame2

In [ ]:
states = ["Texas", "Utah", "California"]

In [ ]:
frame.reindex(columns=states)

In [ ]:
frame.reindex(states, axis="columns")

In [ ]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

In [ ]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])

In [ ]:
obj

In [ ]:
new_obj = obj.drop("c")

In [ ]:
new_obj

In [ ]:
obj.drop(["d", "c"])

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=["Ohio", "Colorado", "Utah", "New York"],
                   columns=["one", "two", "three", "four"])

In [ ]:
data

In [ ]:
data.drop(index=["Colorado", "Ohio"])

In [ ]:
data.drop(columns=["two"])

In [ ]:
data.drop("two", axis=1)

In [ ]:
data.drop(["two", "four"], axis="columns")

In [ ]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])

In [ ]:
obj

In [ ]:
obj["b"]

In [ ]:
obj[1]

In [ ]:
obj[2:4]

In [ ]:
obj[["b", "a", "d"]]

In [ ]:
obj[[1, 3]]

In [ ]:
obj[obj < 2]

In [ ]:
obj.loc[["b", "a", "d"]]

In [ ]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])

In [ ]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [ ]:
obj1

In [ ]:
obj2

In [ ]:
obj1[[0, 1, 2]]

In [ ]:
obj2[[0, 1, 2]]

In [ ]:
obj2.loc[[0, 1]]

In [ ]:
obj1.loc[[0, 1, 2]]

In [ ]:
obj2.iloc[[0, 1, 2]]

In [ ]:
obj2.loc["b":"c"] = 5

In [ ]:
obj2

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=["Ohio", "Colorado", "Utah", "New York"],
                   columns=["one", "two", "three", "four"])

In [ ]:
data

In [ ]:
data["two"]

In [ ]:
data[["three", "one"]]

In [ ]:
data[:2]

In [ ]:
data[data["three"] > 5]

In [ ]:
data < 5

In [ ]:
data[data < 5] = 0

In [ ]:
data

In [ ]:
data

In [ ]:
data.loc["Colorado"]

In [ ]:
data.loc[["Colorado", "New York"]]

In [ ]:
data.loc["Colorado", ["two", "three"]]

In [ ]:
data.iloc[2]

In [ ]:
data.iloc[[2, 1]]

In [ ]:
data.iloc[2, [3, 0, 1]]

In [ ]:
data.iloc[[1, 2], [3, 0, 1]]

In [ ]:
data.loc[:"Utah", "two"]

In [ ]:
data.iloc[:, :3][data.three > 5]

In [ ]:
data.loc[data.three >= 2]

In [ ]:
ser = pd.Series(np.arange(3.))

In [ ]:
ser

In [ ]:
ser[-1]

In [ ]:
ser

In [ ]:
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])

In [ ]:
ser2[-1]

In [ ]:
ser.iloc[-1]

In [ ]:
ser[:2]

In [ ]:
data.loc[:, "one"] = 1

In [ ]:
data

In [ ]:
data.iloc[2] = 5

In [ ]:
data

In [ ]:
data.loc[data["four"] > 5] = 3

In [ ]:
data

In [ ]:
data.loc[data.three == 5, "three"] = 6

In [ ]:
data

In [ ]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])

In [ ]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=["a", "c", "e", "f", "g"])

In [ ]:
s1

In [ ]:
s2

In [ ]:
s1 + s2

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                  index=["Ohio", "Texas", "Colorado"])

In [ ]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                  index=["Utah", "Ohio", "Texas", "Oregon"])

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1 + df2

In [ ]:
df1 = pd.DataFrame({"A": [1, 2]})

In [ ]:
df2 = pd.DataFrame({"B": [3, 4]})

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1 + df2

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                  columns=list("abcd"))

In [ ]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns=list("abcde"))

In [ ]:
df2.loc[1, "b"] = np.nan

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1 + df2

In [ ]:
df1.add(df2, fill_value=0)

In [ ]:
1 / df1

In [ ]:
df1.rdiv(1)

In [ ]:
df1.reindex(columns=df2.columns, fill_value=0)

In [78]:
arr = np.arange(12.).reshape((3, 4))

In [79]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [80]:
arr[0]

array([0., 1., 2., 3.])

In [81]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [82]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list("bde"),
                    index=["Utah", "Ohio", "Texas", "Oregon"])

In [84]:
series = frame.iloc[0]

In [85]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [86]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [87]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [88]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])

In [89]:
series2

b    0
e    1
f    2
dtype: int32

In [90]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [91]:
series3 = frame["d"]

In [92]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [93]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [94]:
frame.sub(series3, axis="index")

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [95]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                    columns=list("bde"),
                    index=["Utah", "Ohio", "Texas", "Oregon"])

In [96]:
frame

b         d         e
Utah    0.120765  0.313945  0.450793
Ohio   -0.343606  0.617559 -0.017629
Texas   0.490778  0.140833  0.544076
Oregon -1.085455 -0.137456 -0.975862

In [97]:
np.abs(frame)

b         d         e
Utah    0.120765  0.313945  0.450793
Ohio    0.343606  0.617559  0.017629
Texas   0.490778  0.140833  0.544076
Oregon  1.085455  0.137456  0.975862

In [98]:
def f1(x):
    return x.max() - x.min()

In [99]:
frame.apply(f1)

b    1.576233
d    0.755016
e    1.519938
dtype: float64

In [100]:
frame.apply(f1, axis="columns")

Utah      0.330028
Ohio      0.961165
Texas     0.403244
Oregon    0.947999
dtype: float64

In [101]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

In [102]:
frame.apply(f2)

b         d         e
min -1.085455 -0.137456 -0.975862
max  0.490778  0.617559  0.544076

In [105]:
def my_format(x):
    return f"{x:.2f}"

In [106]:
frame.applymap(my_format)

b      d      e
Utah     0.12   0.31   0.45
Ohio    -0.34   0.62  -0.02
Texas    0.49   0.14   0.54
Oregon  -1.09  -0.14  -0.98

In [107]:
frame["e"].map(my_format)

Utah       0.45
Ohio      -0.02
Texas      0.54
Oregon    -0.98
Name: e, dtype: object

In [108]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

In [109]:
obj

d    0
a    1
b    2
c    3
dtype: int32

In [110]:
obj.sort_index

<bound method Series.sort_index of d    0
a    1
b    2
c    3
dtype: int32>

In [111]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=["three", "one"],
                    columns=["d", "a", "b", "c"]) 

In [112]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [113]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [114]:
frame.sort_index(axis="columns")

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [115]:
frame.sort_index(axis="columns", ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [116]:
obj = pd.Series([4, 7, -3, 2])

In [117]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [118]:
obj = pd.Series([4, np.nan, 7, np.nan -3, 2])

In [119]:
obj.sort_values()

4    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [120]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4    2.0
0    4.0
2    7.0
dtype: float64

In [121]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})

In [122]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [123]:
frame.sort_values("b")

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [124]:
frame.sort_values(["a", "b"])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [125]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [126]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [127]:
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [128]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [129]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1], 
                     "c": [-2, 6, 8, -2.5]})

In [130]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  6.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [131]:
frame.rank(axis="columns")

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [132]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])

In [133]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [134]:
obj.index.is_unique

False

In [135]:
obj["a"]

a    0
a    1
dtype: int32

In [136]:
obj["c"]

4

In [137]:
df = pd.DataFrame(np.random.standard_normal((5, 3)),
                 index=["a", "a", "b", "b", "c"])

In [138]:
df

0         1         2
a -1.374568 -0.455639  0.090261
a  1.190650 -1.748401 -0.577110
b  0.377687  0.684428  1.192918
b -0.582790  1.052274  0.519018
c  1.054362  1.094326 -0.420264

In [139]:
df.loc["b"]

0         1         2
b  0.377687  0.684428  1.192918
b -0.582790  1.052274  0.519018

In [140]:
df.loc["c"]

0    1.054362
1    1.094326
2   -0.420264
Name: c, dtype: float64

In [141]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75, -1.3]],
                 index=["a", "b", "c", "d"], 
                 columns=["one", "two"])

In [142]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [143]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [144]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [145]:
df.sum(axis="index", skipna=False)

one   NaN
two   NaN
dtype: float64

In [146]:
df.sum(axis="index", skipna=False)

one   NaN
two   NaN
dtype: float64

In [147]:
df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [148]:
df.idxmax()

one    b
two    d
dtype: object

In [149]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [150]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [154]:
obj = pd.Series(["a", "a", "b", "c"] * 4)

In [155]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [156]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [157]:
price = pd.read_pickle("./yahoo_price.pkl")

In [158]:
volume = pd.read_pickle("./yahoo_volume.pkl")

In [160]:
returns = price.pct_change()

In [161]:
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [162]:
returns["MSFT"].corr(returns["IBM"])

0.4997636114415114

In [163]:
returns["MSFT"].cov(returns["IBM"])

8.870655479703546e-05

In [164]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [165]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [167]:
returns.corrwith(returns["IBM"])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [168]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

In [169]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [170]:
uniques = obj.unique()

In [171]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [172]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [174]:
pd.value_counts(obj.to_numpy(), sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [175]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [176]:
mask = obj.isin(["b", "c"])

In [177]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [178]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [179]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])

In [180]:
unique_vals = pd.Series(["c", "b", "a"])

In [181]:
indices = pd.Index(unique_vals).get_indexer(to_match)

In [182]:
indices

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [183]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
                     "Qu2": [2, 3, 1, 2, 3],
                     "Qu3": [1, 5, 2, 4, 4],
                    })

In [184]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [185]:
data["Qu1"].value_counts().sort_index()

1    1
3    2
4    2
Name: Qu1, dtype: int64

In [186]:
result = data.apply(pd.value_counts).fillna(0)

In [187]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [189]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})

In [190]:
data

a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [191]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
dtype: int64